### ISSUE TITLE
Can't install in GBK locale

### ISSUE THREAD

**Issue by ZisIsNotZis** [yuxiangw/autodp#37]
`pip install autodp` will fail like below. The setup script should specify an encoding in `open(...)`.

```cmd
C:\Users\xxx>pip install autodp
Looking in indexes: https://mirror.baidu.com/pypi/simple
Collecting autodp
  Using cached https://mirror.baidu.com/pypi/packages/78/7c/63aa6d37b9d9f0f68d1231e1b3247c3ac83c634f451f8bcbd9a5c7a55db0/autodp-0.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-l8spogwd\autodp_e20c1a3119ab4b0c8d685149702e4657\setup.py", line 6, in <module>
          long_description = f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 3594: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'd:\pysyft\Scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by bear-zd** [comment]
there is a method to solve this problem. This problem happened when setup.py try to read a README.md as a wrong decode method( however not needed).
To solve this error, you should download this repo(or `git clone https://github.com/yuxiangw/autodp.git`). Then edit the setup.py.Delete the line :
`with open("README.md", 'r') as f:
    long_description = f.read()`
Then run the `pip install -e .` command to setup this package. Hope this can help you.
